# Translations template for cinder.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# Ettore Atalan <atalanttore@googlemail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Cinder\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-11 06:09+0000\n"
"PO-Revision-Date: 2014-11-10 13:52+0000\n"
"Last-Translator: Ettore Atalan <atalanttore@googlemail.com>\n"
"Language-Team: German (http://www.transifex.com/projects/p/cinder/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: cinder/backup/manager.py:445
msgid "Failed to update usages deleting backup"
msgstr ""

#: cinder/backup/manager.py:629
msgid "Backup driver has not been initialized"
msgstr "Datensicherungstreiber wurde nicht initialisiert"

#: cinder/backup/drivers/ceph.py:459
#, python-format
msgid ""
"Max retries reached deleting backup %(basename)s image of volume %(volume)s."
msgstr ""

#: cinder/backup/drivers/ceph.py:495
#, python-format
msgid "Pipe1 failed - %s "
msgstr ""

#: cinder/backup/drivers/ceph.py:509
#, python-format
msgid "Pipe2 failed - %s "
msgstr ""

#: cinder/backup/drivers/ceph.py:973
msgid "Differential restore failed, trying full restore"
msgstr ""

#: cinder/backup/drivers/ceph.py:1175
#, python-format
msgid "Restore to volume %(volume)s finished with error - %(error)s."
msgstr ""

#: cinder/backup/drivers/swift.py:159
#, python-format
msgid "single_user auth mode enabled, but %(param)s not set"
msgstr ""

#: cinder/backup/drivers/swift.py:394
#, python-format
msgid "Backup volume metadata to swift failed: %s"
msgstr ""

#: cinder/backup/drivers/tsm.py:252
#, python-format
msgid ""
"backup: %(vol_id)s failed to remove backup hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""

#: cinder/backup/drivers/tsm.py:531
#, python-format
msgid ""
"delete: %(vol_id)s failed with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:50
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:75
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:106
#, python-format
msgid "Table |%s| not created!"
msgstr "Tabelle |%s| nicht erstellt!"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:128
msgid "Dropping foreign key reservations_ibfk_1 failed."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:134
msgid "quota_classes table not dropped"
msgstr "'quota_classes'-Tabelle nicht gelöscht"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:141
msgid "quota_usages table not dropped"
msgstr "quota_usages-Tabelle nicht gelöscht"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:148
msgid "reservations table not dropped"
msgstr "reservations-Tabelle nicht gelöscht"

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:32
msgid "migrations table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:62
#, python-format
msgid "Table |%s| not created"
msgstr "Tabelle |%s| nicht erstellt"

#: cinder/db/sqlalchemy/migrate_repo/versions/021_add_default_quota_class.py:76
msgid "Default quota class data not inserted into the DB."
msgstr ""

#: cinder/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Ursprüngliche Ausnahme wird gelöscht: %s"

#: cinder/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Unerwartete Ausnahme %d mal(e) aufgetreten... Neuversuch."

#: cinder/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "in Schleifenaufruf mit festgelegter Dauer"

#: cinder/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "in dynamischen Schleifenaufruf"

#: cinder/openstack/common/periodic_task.py:202
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "Fehler bei %(full_task_name)s: %(e)s"

#: cinder/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "Regel %s konnte nicht verstanden werden"

#: cinder/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Kein Handler für Übereinstimmungen des Typs %s"

#: cinder/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "Regel %r konnte nicht verstanden werden"

#: cinder/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Ausnahme bei RPC Cleanup."

#: cinder/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Nicht behandelte Ausnahme"
